version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gradle
    directory: "/androidApp"
    schedule:
      day: sunday
      interval: weekly